// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: chat_gpt
//
// Hand-edited: Region Select dropdown removed and replaced with a Device Name
// textarea + shared on-screen keyboard. If the SquareLine project is
// regenerated, re-apply the Device Name block and delete the Region block.
// See CLAUDE.md "Architecture in one pass" for details.

#include <stdio.h>

#include "../ui.h"
#include "settings.h"

void ui_ScreenSettings_screen_init(void)
{
    ui_ScreenSettings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScreenSettings, &ui_img_setup_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSettingsTile = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_LabelSettingsTile, 230);
    lv_obj_set_height(ui_LabelSettingsTile, 23);
    lv_obj_set_x(ui_LabelSettingsTile, 45);
    lv_obj_set_y(ui_LabelSettingsTile, 15);
    lv_label_set_text(ui_LabelSettingsTile, "Settings");
    lv_obj_set_style_text_color(ui_LabelSettingsTile, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSettingsTile, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSettingsTile, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSettingsTile, &ui_font_PingFangEN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSettings = lv_obj_create(ui_ScreenSettings);
    lv_obj_set_width(ui_PanelSettings, lv_pct(100));
    lv_obj_set_height(ui_PanelSettings, lv_pct(79));
    lv_obj_set_align(ui_PanelSettings, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_PanelSettings, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelSettings, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_set_style_radius(ui_PanelSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_PanelSettings, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelSettings, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelSettings, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelSettings, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelSettings, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelSettings, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelSettings, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelSettings, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelSettings, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_PanelSettingsSplitBar = lv_obj_create(ui_PanelSettings);
    lv_obj_set_width(ui_PanelSettingsSplitBar, lv_pct(100));
    lv_obj_set_height(ui_PanelSettingsSplitBar, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_PanelSettingsSplitBar, -2);
    lv_obj_set_y(ui_PanelSettingsSplitBar, 47);
    lv_obj_set_align(ui_PanelSettingsSplitBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSettingsSplitBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSettingsSplitBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSettingsSplitBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSettingsSplitBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSettingsSplitBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelSettingsSplitBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelSettingsSplitBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelSettingsSplitBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelSettingsSplitBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelSettingsSplitBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelSettingsSplitBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSettingsSplitBarLeft = lv_obj_create(ui_PanelSettingsSplitBar);
    lv_obj_set_height(ui_PanelSettingsSplitBarLeft, 2);
    lv_obj_set_width(ui_PanelSettingsSplitBarLeft, lv_pct(50));
    lv_obj_set_align(ui_PanelSettingsSplitBarLeft, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_PanelSettingsSplitBarLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSettingsSplitBarLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSettingsSplitBarLeft, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSettingsSplitBarLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PanelSettingsSplitBarLeft, lv_color_hex(0x6E47BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelSettingsSplitBarLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelSettingsSplitBarLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PanelSettingsSplitBarLeft, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSettingsSplitBarLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsSettingsSplitBarRight = lv_obj_create(ui_PanelSettingsSplitBar);
    lv_obj_set_height(ui_SettingsSettingsSplitBarRight, 2);
    lv_obj_set_width(ui_SettingsSettingsSplitBarRight, lv_pct(50));
    lv_obj_set_align(ui_SettingsSettingsSplitBarRight, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_SettingsSettingsSplitBarRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettingsSettingsSplitBarRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SettingsSettingsSplitBarRight, lv_color_hex(0x6E47BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsSettingsSplitBarRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SettingsSettingsSplitBarRight, lv_color_hex(0x000000),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SettingsSettingsSplitBarRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SettingsSettingsSplitBarRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SettingsSettingsSplitBarRight, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingsSettingsSplitBarRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Hand-edit: Device Name row (replaces the removed Region Select). */
    ui_PanelSettingsDeviceName = lv_obj_create(ui_PanelSettings);
    lv_obj_set_width(ui_PanelSettingsDeviceName, lv_pct(100));
    lv_obj_set_height(ui_PanelSettingsDeviceName, lv_pct(19));
    lv_obj_set_align(ui_PanelSettingsDeviceName, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_PanelSettingsDeviceName, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelSettingsDeviceName, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSettingsDeviceName, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_PanelSettingsDeviceName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSettingsDeviceName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSettingsDeviceName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelSettingsDeviceName, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelSettingsDeviceName, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelSettingsDeviceName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelSettingsDeviceName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSettingsDeviceName = lv_label_create(ui_PanelSettingsDeviceName);
    lv_obj_set_width(ui_LabelSettingsDeviceName, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LabelSettingsDeviceName, LV_SIZE_CONTENT);
    lv_label_set_text(ui_LabelSettingsDeviceName, "Device Name");
    lv_obj_set_style_text_color(ui_LabelSettingsDeviceName, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSettingsDeviceName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSettingsDeviceName, &ui_font_PingFangEN16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextareaSettingsDeviceName = lv_textarea_create(ui_PanelSettingsDeviceName);
    lv_textarea_set_one_line(ui_TextareaSettingsDeviceName, true);
    lv_textarea_set_max_length(ui_TextareaSettingsDeviceName, DEVICE_NAME_SIZE - 1);
    lv_textarea_set_placeholder_text(ui_TextareaSettingsDeviceName, "Satellite");
    lv_textarea_set_text(ui_TextareaSettingsDeviceName, settings_get_parameter()->device_name);
    lv_obj_set_width(ui_TextareaSettingsDeviceName, lv_pct(55));
    lv_obj_set_height(ui_TextareaSettingsDeviceName, LV_SIZE_CONTENT);
    lv_obj_add_event_cb(ui_TextareaSettingsDeviceName, ui_event_TextareaSettingsDeviceName, LV_EVENT_ALL, NULL);

    /* Hand-edit: Listen Cap slider row (runtime-editable LISTEN wall-clock cap). */
    ui_PanelSettingsListenCap = lv_obj_create(ui_PanelSettings);
    lv_obj_set_width(ui_PanelSettingsListenCap, lv_pct(100));
    lv_obj_set_height(ui_PanelSettingsListenCap, lv_pct(19));
    lv_obj_set_flex_flow(ui_PanelSettingsListenCap, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelSettingsListenCap, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSettingsListenCap, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_PanelSettingsListenCap, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSettingsListenCap, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSettingsListenCap, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelSettingsListenCap, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelSettingsListenCap, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelSettingsListenCap, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelSettingsListenCap, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSettingsListenCap = lv_label_create(ui_PanelSettingsListenCap);
    lv_obj_set_width(ui_LabelSettingsListenCap, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LabelSettingsListenCap, LV_SIZE_CONTENT);
    lv_label_set_text(ui_LabelSettingsListenCap, "Listen Cap");
    lv_obj_set_style_text_color(ui_LabelSettingsListenCap, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSettingsListenCap, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSettingsListenCap, &ui_font_PingFangEN16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSettingsListenCap = lv_slider_create(ui_PanelSettingsListenCap);
    lv_slider_set_range(ui_SliderSettingsListenCap, LISTEN_CAP_S_MIN, LISTEN_CAP_S_MAX);
    lv_slider_set_value(ui_SliderSettingsListenCap,
                        settings_get_parameter()->listen_cap_s, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSettingsListenCap, lv_pct(40));
    lv_obj_set_height(ui_SliderSettingsListenCap, 10);
    lv_obj_add_event_cb(ui_SliderSettingsListenCap, ui_event_SliderSettingsListenCap, LV_EVENT_ALL, NULL);

    ui_LabelSettingsListenCapValue = lv_label_create(ui_PanelSettingsListenCap);
    lv_obj_set_width(ui_LabelSettingsListenCapValue, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LabelSettingsListenCapValue, LV_SIZE_CONTENT);
    {
        char buf[12];
        snprintf(buf, sizeof(buf), "%lus",
                 (unsigned long)settings_get_parameter()->listen_cap_s);
        lv_label_set_text(ui_LabelSettingsListenCapValue, buf);
    }
    lv_obj_set_style_text_color(ui_LabelSettingsListenCapValue, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSettingsListenCapValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSettingsListenCapValue, &ui_font_PingFangEN16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Hand-edit: Silence Timeout slider row (runtime-editable end-of-utterance cutoff). */
    ui_PanelSettingsSilence = lv_obj_create(ui_PanelSettings);
    lv_obj_set_width(ui_PanelSettingsSilence, lv_pct(100));
    lv_obj_set_height(ui_PanelSettingsSilence, lv_pct(19));
    lv_obj_set_flex_flow(ui_PanelSettingsSilence, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelSettingsSilence, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSettingsSilence, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_PanelSettingsSilence, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSettingsSilence, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSettingsSilence, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelSettingsSilence, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelSettingsSilence, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelSettingsSilence, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelSettingsSilence, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSettingsSilence = lv_label_create(ui_PanelSettingsSilence);
    lv_obj_set_width(ui_LabelSettingsSilence, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LabelSettingsSilence, LV_SIZE_CONTENT);
    lv_label_set_text(ui_LabelSettingsSilence, "Silence");
    lv_obj_set_style_text_color(ui_LabelSettingsSilence, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSettingsSilence, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSettingsSilence, &ui_font_PingFangEN16, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* 100 ms step — the underlying cutoff is frame-quantised at 20 ms so
     * finer steps would be visually noisy without changing behaviour. */
    ui_SliderSettingsSilence = lv_slider_create(ui_PanelSettingsSilence);
    lv_slider_set_range(ui_SliderSettingsSilence,
                        SILENCE_MS_MIN / 100, SILENCE_MS_MAX / 100);
    lv_slider_set_value(ui_SliderSettingsSilence,
                        settings_get_parameter()->silence_ms / 100, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSettingsSilence, lv_pct(40));
    lv_obj_set_height(ui_SliderSettingsSilence, 10);
    lv_obj_add_event_cb(ui_SliderSettingsSilence, ui_event_SliderSettingsSilence, LV_EVENT_ALL, NULL);

    ui_LabelSettingsSilenceValue = lv_label_create(ui_PanelSettingsSilence);
    lv_obj_set_width(ui_LabelSettingsSilenceValue, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LabelSettingsSilenceValue, LV_SIZE_CONTENT);
    {
        char buf[12];
        uint32_t ms = settings_get_parameter()->silence_ms;
        snprintf(buf, sizeof(buf), "%lu.%lus",
                 (unsigned long)(ms / 1000), (unsigned long)((ms % 1000) / 100));
        lv_label_set_text(ui_LabelSettingsSilenceValue, buf);
    }
    lv_obj_set_style_text_color(ui_LabelSettingsSilenceValue, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSettingsSilenceValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSettingsSilenceValue, &ui_font_PingFangEN16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Hand-edit: Follow-Up window slider row (post-playback no-wake-word
     * listen window). 0 = disabled. */
    ui_PanelSettingsFollowUp = lv_obj_create(ui_PanelSettings);
    lv_obj_set_width(ui_PanelSettingsFollowUp, lv_pct(100));
    lv_obj_set_height(ui_PanelSettingsFollowUp, lv_pct(19));
    lv_obj_set_flex_flow(ui_PanelSettingsFollowUp, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelSettingsFollowUp, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSettingsFollowUp, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_PanelSettingsFollowUp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSettingsFollowUp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSettingsFollowUp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelSettingsFollowUp, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelSettingsFollowUp, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelSettingsFollowUp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelSettingsFollowUp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSettingsFollowUp = lv_label_create(ui_PanelSettingsFollowUp);
    lv_obj_set_width(ui_LabelSettingsFollowUp, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LabelSettingsFollowUp, LV_SIZE_CONTENT);
    lv_label_set_text(ui_LabelSettingsFollowUp, "Follow-Up");
    lv_obj_set_style_text_color(ui_LabelSettingsFollowUp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSettingsFollowUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSettingsFollowUp, &ui_font_PingFangEN16, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* 1 s step. Range 0..15 — 0 displays as "Off" and disables the
     * follow-up window entirely (back to "Hey Selene" required). */
    ui_SliderSettingsFollowUp = lv_slider_create(ui_PanelSettingsFollowUp);
    lv_slider_set_range(ui_SliderSettingsFollowUp,
                        FOLLOW_UP_MS_MIN / 1000, FOLLOW_UP_MS_MAX / 1000);
    lv_slider_set_value(ui_SliderSettingsFollowUp,
                        settings_get_parameter()->follow_up_ms / 1000, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSettingsFollowUp, lv_pct(40));
    lv_obj_set_height(ui_SliderSettingsFollowUp, 10);
    lv_obj_add_event_cb(ui_SliderSettingsFollowUp, ui_event_SliderSettingsFollowUp, LV_EVENT_ALL, NULL);

    ui_LabelSettingsFollowUpValue = lv_label_create(ui_PanelSettingsFollowUp);
    lv_obj_set_width(ui_LabelSettingsFollowUpValue, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LabelSettingsFollowUpValue, LV_SIZE_CONTENT);
    {
        uint32_t s = settings_get_parameter()->follow_up_ms / 1000;
        if (s == 0) {
            lv_label_set_text(ui_LabelSettingsFollowUpValue, "Off");
        } else {
            char buf[12];
            snprintf(buf, sizeof(buf), "%lus", (unsigned long)s);
            lv_label_set_text(ui_LabelSettingsFollowUpValue, buf);
        }
    }
    lv_obj_set_style_text_color(ui_LabelSettingsFollowUpValue, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSettingsFollowUpValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSettingsFollowUpValue, &ui_font_PingFangEN16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Hand-edit: Update Firmware row. Tap → havencore_ota_pull() against
     * ${Base_url}/firmware/satellite.bin. Wires through
     * EventButtonSettingsUpdate in main/app/app_ui_events.c. */
    ui_PanelSettingsUpdate = lv_obj_create(ui_PanelSettings);
    lv_obj_set_width(ui_PanelSettingsUpdate, lv_pct(100));
    lv_obj_set_height(ui_PanelSettingsUpdate, lv_pct(19));
    lv_obj_set_flex_flow(ui_PanelSettingsUpdate, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelSettingsUpdate, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSettingsUpdate, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_PanelSettingsUpdate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSettingsUpdate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSettingsUpdate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelSettingsUpdate, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelSettingsUpdate, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelSettingsUpdate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelSettingsUpdate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSettingsUpdate = lv_label_create(ui_PanelSettingsUpdate);
    lv_obj_set_width(ui_LabelSettingsUpdate, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LabelSettingsUpdate, LV_SIZE_CONTENT);
    lv_label_set_text(ui_LabelSettingsUpdate, "Firmware");
    lv_obj_set_style_text_color(ui_LabelSettingsUpdate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSettingsUpdate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSettingsUpdate, &ui_font_PingFangEN16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSettingsUpdate = lv_btn_create(ui_PanelSettingsUpdate);
    lv_obj_set_width(ui_ButtonSettingsUpdate, lv_pct(35));
    lv_obj_set_height(ui_ButtonSettingsUpdate, 30);
    lv_obj_clear_flag(ui_ButtonSettingsUpdate, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_ButtonSettingsUpdate, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonSettingsUpdate, lv_color_hex(0x2C7BE5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonSettingsUpdate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_ButtonSettingsUpdate, ui_event_ButtonSettingsUpdate, LV_EVENT_ALL, NULL);

    ui_LabelSettingsUpdateBtn = lv_label_create(ui_ButtonSettingsUpdate);
    lv_label_set_text(ui_LabelSettingsUpdateBtn, "Update");
    lv_obj_set_style_text_color(ui_LabelSettingsUpdateBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSettingsUpdateBtn, &ui_font_PingFangEN16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_center(ui_LabelSettingsUpdateBtn);

    /* Shared on-screen keyboard. Parented to the screen (not the row panel)
     * so it can span the full width and float above other widgets. Hidden
     * until the textarea is focused. */
    ui_KeyboardSettings = lv_keyboard_create(ui_ScreenSettings);
    lv_obj_set_width(ui_KeyboardSettings, lv_pct(100));
    lv_obj_set_height(ui_KeyboardSettings, lv_pct(50));
    lv_obj_align(ui_KeyboardSettings, LV_ALIGN_BOTTOM_MID, 0, 0);
    lv_obj_add_flag(ui_KeyboardSettings, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_event_cb(ui_KeyboardSettings, ui_event_KeyboardSettings, LV_EVENT_ALL, NULL);

    ui_ImageSettingsBack = lv_img_create(ui_ScreenSettings);
    lv_img_set_src(ui_ImageSettingsBack, &ui_img_settings_back_png);
    lv_obj_set_width(ui_ImageSettingsBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageSettingsBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageSettingsBack, 10);
    lv_obj_set_y(ui_ImageSettingsBack, 10);
    lv_obj_add_flag(ui_ImageSettingsBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_add_flag(ui_ImageSettingsBack, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSettingsBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_border_color(ui_ImageSettingsBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ImageSettingsBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ImageSettingsBack, 5, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_ImageSettingsReset = lv_img_create(ui_ScreenSettings);
    lv_img_set_src(ui_ImageSettingsReset, &ui_img_reset_icon_png);
    lv_obj_set_width(ui_ImageSettingsReset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageSettingsReset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageSettingsReset, -10);
    lv_obj_set_y(ui_ImageSettingsReset, 10);
    lv_obj_set_align(ui_ImageSettingsReset, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ImageSettingsReset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_add_flag(ui_ImageSettingsReset, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSettingsReset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_border_color(ui_ImageSettingsReset, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ImageSettingsReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ImageSettingsReset, 5, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_add_event_cb(ui_ImageSettingsBack, ui_event_ImageSettingsBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImageSettingsReset, ui_event_ImageSettingsReset, LV_EVENT_ALL, NULL);
}
