// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: chat_gpt_new_gui

#include "app_sr.h"

#include "ui.h"
#include "app_ui_ctrl.h"
#include "settings.h"
#include "esp_system.h"
#include "esp_log.h"

static char *TAG = "ui-events";

void EventBtnSetupClick(lv_event_t *e)
{
    // Your code here
    ui_sleep_show_animation();
}

void EventPanelSleepClickCb(lv_event_t *e)
{
    // Your code here
    app_sr_start_once();
    ESP_LOGI(TAG, "sr start once");
}

static void trigger_factory_reset(const char *source)
{
    ESP_LOGI(TAG, "Factory reset requested from %s", source);
    esp_err_t err = settings_factory_reset();
    /* settings_factory_reset() restarts on success, so anything that
     * returns here is a failure — ota_0 is blank/corrupt and the UF2
     * recovery app cannot run. Surface it on-screen rather than letting
     * the UI sit frozen. */
    ESP_LOGE(TAG, "factory reset failed: %s", esp_err_to_name(err));
    ui_ctrl_show_fatal_error(
        "UF2 recovery image missing.\n"
        "Run scripts/bootstrap_ota0.sh on\n"
        "the host, then retry.");
}

void EventWifiResetConfirmClick(lv_event_t *e)
{
    trigger_factory_reset("WIFI reset page");
}

void EventResetConfirm(lv_event_t *e)
{
    trigger_factory_reset("Settings page");
}
